# Generated by Django 4.1 on 2023-09-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="channel_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ID", models.TextField()),
                ("Title", models.TextField()),
                ("Duration", models.TextField()),
                ("Views", models.BigIntegerField()),
                ("Likes", models.BigIntegerField()),
                ("Comments", models.BigIntegerField()),
                ("LikesPerView", models.FloatField()),
                ("CommentsPerView", models.FloatField()),
                ("LikesPerComment", models.FloatField()),
            ],
        ),
    ]
