# Generated by Django 4.1 on 2023-09-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="channel_data", new_name="youtube_app_channel_data_1",
        ),
    ]
